-- insertando el menu de la polleria
-- Platos de Pollo a la Brasa
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('P001', 'Pollo San Pedro', 51.00, 'Brasa', 'Pollo San Pedro con 1/2 porción de papa frita');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('P002', 'Pollo San Pedro', 57.00, 'Brasa', 'Pollo San Pedro con 1/2 porción de papa frita y ensalada');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('P003', 'Pollo San Pedro', 71.00, 'Brasa', 'Pollo San Pedro con 1/2 porción de papa frita, ensalada y 1.5 L de Inca Kola');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('P004', 'Pollo San Pedro', 76.00, 'Brasa', 'Pollo San Pedro con 1/2 porción de papa frita, ensalada y 1.5 L de Inca Kola');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('P005', '1/2 Pollo San Pedro', 38.50, 'Brasa', '1/2 Pollo San Pedro con papa frita y 2 Pepsi 500ml');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('P006', '1/4 Pollo San Pedro', 24.50, 'Brasa', '1/4 Pollo San Pedro con ensalada personal y 1 Pepsi 500ml');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('P007', 'Pollo San Pedro', 44.00, 'Brasa', 'Pollo San Pedro sin acompañamientos');

-- Platos Criollos
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('C001', 'Lomo Saltado', 28.00, 'Criollo', 'Lomo Saltado tradicional con guarnición de arroz y papas');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('C002', 'Saltado de Pollo', 21.50, 'Criollo', 'Saltado de Pollo acompañado de arroz y papas fritas');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('C003', 'Tallarín Saltado de Res', 25.50, 'Criollo', 'Tallarín Saltado con carne de res y vegetales');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('C004', 'Tallarín Saltado de Pollo', 21.50, 'Criollo', 'Tallarín Saltado con pollo y vegetales');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('C005', 'Milanesa de Pollo', 16.50, 'Criollo', 'Milanesa de Pollo empanizada con guarnición');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('C006', 'Filete de Pollo', 16.50, 'Criollo', 'Filete de Pollo a la plancha con guarnición');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('C007', 'Caldo de Gallina', 17.00, 'Criollo', 'Caldo de Gallina tradicional');
INSERT INTO PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, CATEGORIA, DESCRIPCION)
VALUES ('C008', 'Salchipapa', 12.00, 'Criollo', 'Salchicha frita con papas');



-- Gaseosas
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B001', 'Coca Cola', 8.50, 'Gaseosa', '1.5L', 'Botella de Coca Cola de 1.5L');
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B002', 'Inca Kola', 8.50, 'Gaseosa', '1.5L', 'Botella de Inca Kola de 1.5L');
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B003', 'Coca Cola', 5.50, 'Gaseosa', '500ml', 'Botella de Coca Cola de 500ml');
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B004', 'Inca Kola', 5.50, 'Gaseosa', '500ml', 'Botella de Inca Kola de 500ml');
-- Agua
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B005', 'Agua San Mateo', 3.00, 'Agua', '600ml', 'Botella de agua San Mateo de 600ml');
-- Jugos
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B006', 'Limonada', 4.00, 'Jugo', '1L', 'Jarra de limonada de 1L');
-- Infusiones
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B007', 'Té/Infusión de Canela y Clavo', 2.50, 'Jugo', 'N/A', 'Infusión de té con canela y clavo');
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B008', 'Anís/Manzanilla', 2.50, 'Jugo', 'N/A', 'Infusión de anís o manzanilla');
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B009', 'Café', 2.50, 'Jugo', 'N/A', 'Café');
-- Bebidas Alcohólicas
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B010', 'Sangría', 40.00, 'Alcohol', 'Jarra', 'Jarra de sangría tradicional');
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B011', 'Sangría', 12.00, 'Alcohol', 'Copa', 'Copa de sangría tradicional');
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B012', 'Vino Tacama Rosé', 50.00, 'Alcohol', '750ml', 'Botella de vino Tacama Rosé de 750ml');
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B013', 'Chicha', 8.00, 'Alcohol', '1L', 'Jarra de chicha de 1L');
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B014', 'Vino Tabernero Rosado', 40.00, 'Alcohol', '750ml', 'Botella de vino Tabernero Rosado de 750ml');
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B015', 'Cerveza Pilsen Trujillo', 9.00, 'Alcohol', '330ml', 'Botella de cerveza Pilsen Trujillo');
INSERT INTO BEBIDA (ID_BEBIDA, NOMBRE, PRECIO, CATEGORIA, TAMANO, DESCRIPCION)
VALUES ('B016', 'Cerveza Cusqueña', 9.00, 'Alcohol', '330ml', 'Botella de cerveza Cusqueña');

-- Papas fritas
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G001', '1', 'Papas Fritas', 14.00, 1, 'Porc.');
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G002', '1/2', 'Papas Fritas', 7.50, 1, 'Porc.');
-- Ensalada mixta
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G003', '1', 'Ensalada Mixta', 10.00, 1, 'Porc.');
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G004', '1/2', 'Ensalada Mixta', 5.00, 1, 'Porc.');
-- Arroz
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G005', '1', 'Arroz', 3.00, 1, 'Porc.');
-- Hot Dog
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G006', '1', 'Hot Dog', 3.00, 1, 'Unid.');
-- Huevo frito
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G007', '1', 'Huevo Frito', 1.50, 1, 'Unid.');
-- Huevo sancochado
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G008', '1', 'Huevo Sancochado', 1.50, 1, 'Unid.');
-- Mayonesa
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G009', '1', 'Mayonesa', 1.00, 1, 'oz.');
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G010', '2', 'Mayonesa', 2.00, 2, 'oz.');
-- Ají
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G011', '1', 'Ají', 1.00, 1, 'oz.');
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G012', '2', 'Ají', 2.00, 2, 'oz.');
-- Vinagreta
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G013', '1', 'Vinagreta', 1.00, 1, 'oz.');
INSERT INTO GUARNICION (ID_GUARNICION, PORCION, NOMBRE, PRECIO, CANTIDAD, MAGNITUD)
VALUES ('G014', '2', 'Vinagreta', 2.00, 2, 'oz.');




-- Inserción de 20 mesas
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (1, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (2, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (3, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (4, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (5, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (6, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (7, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (8, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (9, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (10, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (11, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (12, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (13, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (14, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (15, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (16, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (17, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (18, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (19, 'Disponible');
INSERT INTO MESA (NUMERO_MESA, ESTADO) VALUES (20, 'Disponible');



-- Inserción de 5 mozos
INSERT INTO MOZO (ID_MOZO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DNI) 
VALUES ('MZ001', 'Carlos', 'Gonzales', 'Ramirez', '987654321', '01234567');
INSERT INTO MOZO (ID_MOZO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DNI) 
VALUES ('MZ002', 'Luis', 'Torres', 'Martinez', '976543210', '12345678');
INSERT INTO MOZO (ID_MOZO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DNI) 
VALUES ('MZ003', 'Ana', 'Huaman', 'Lopez', '965432109', '23456789');
INSERT INTO MOZO (ID_MOZO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DNI) 
VALUES ('MZ004', 'María', 'Pérez', 'Soto', '954321098', '34567890');
INSERT INTO MOZO (ID_MOZO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DNI) 
VALUES ('MZ005', 'Jorge', 'Rojas', 'Vargas', '943210987', '45678901');
